apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: demo
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: clusters
spec:
  # Everything from this repo will be ran in this cluster. You trust me right?
  repo: "https://github.com/saiyam1814/gitopsdaysfleetdemo"
  branch: main
  targets:
  - clusterGroup: production-group
  paths:
  - demo
